#!/usr/bin/perl
##################################################################
#Copyright (C) 2003 Andrew Stitt astitt@sourcemage.org
#Copyright (C) 2003 Source Mage GNU/Linux (www.sourcemage.org)
#
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either
#version 2 of the License, or (at your option) any later
#version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
##################################################################

#0=file list
#1=number to grab
#srand;

#read in a list and randomize it in memory
open FD,$ARGV[0] or die "missing $ARGV[0]";
srand;
while(<FD>){
   my $r = rand @new+1;
   push(@new,$new[$r]);
   $new[$r] = $_;
}
close FD;
#figure out how many to take
if(exists $ARGV[1]){
	$num=$ARGV[1]-1;
}else{
	$num=0;
}
#print out some number of random things from the list we read in
print @new[0..$num];
