#!/usr/bin/perl
##################################################################
#Copyright (C) 2003 Andrew Stitt astitt@sourcemage.org
#Copyright (C) 2003 Source Mage GNU/Linux (www.sourcemage.org)
#
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either
#version 2 of the License, or (at your option) any later
#version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
##################################################################
$\="\n";
sub loadimage{
	my ($input)=@_;
	my %hash;
	open FD,$input or die;
	while(<FD>){
		($md5,@filename)=split;
		$hash{"@filename"}=$md5;
	}
	close FD;
	return %hash;
}

%old=loadimage($ARGV[0]);
%new=loadimage($ARGV[1]);

#for all the new files, if the file didnt exist before, remember it
#(because its a new file and should be beaten with reeds)
open FD,">new.lst";
map{print FD if ! defined $old{$_};} keys %new;
close FD;
#compare md5sums of old files with those of new files
#for all old files, if it is still around and the md5 is different...
#(because the file changed needs fixing (and to be beaten with reeds))
open FD,">different.lst";
map {print FD if defined $new{$_} and defined $old{$_} and $new{$_} ne $old{$_}} keys %old;
close FD;
#for all old files that aren't in the list of new files...
#(because we have to restore it...then beat someone with reeds)
open FD,">deleted.lst";
map{print FD if ! defined $new{$_};} keys %old;
close FD;
